name: Mirror to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # full clone for mirroring

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.gh2glsafe }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          REMOTE_URL="https://oauth2:${GITLAB_TOKEN}@gitlab.com/safe-6g/development/cognitive-coordinator.git"
          git remote add gitlab "$REMOTE_URL"
          git push --mirror gitlab
